server :
  port: 5005
  RunMKod: debug
logger:
  filepath : ../logs/logs.log
  Encoding: json
  level: debug
cors: 
  allowOrigin: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  dnName: car_sale_db
  sslMode: false
redis:
  host: localhost
  port: 6379
  password: password
  db: 0
  minIdleConnections: 100
  poolSize : 5000 
  poolTimeout: 240


